name: Daily Stock Scan
on:
  schedule:
    - cron: '30 13 * * *' # ריצה אוטומטית ב-16:30
  workflow_dispatch: # כפתור להפעלה ידנית

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'
      - name: Install dependencies
        run: pip install yfinance pandas numpy xlsxwriter
      - name: Run Scanner
        env:
          APP_PASSWORD: ${{ secrets.APP_PASSWORD }}
        run: python stock_scanner.py
      - name: Save progress
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add last_run.json
          git commit -m "Update" || exit 0
          git push
